### ISSUE TITLE
unmashall 方法修改

### ISSUE THREAD

**Issue by cctvccav** [liamylian/json-hashids#1]
首先，感谢大佬提供了这么一个方便的包，但是使用中遇到一点问题。

json-iterator提供了两种使用方法，一种是没有error的DecodeInt64，但是错误会被panic。另外一种提供了错误返回 DecodeInt64WithError。建议使用DecodeInt64WithError。
在json.go 的84行开始。
源代码: 
`ints, err := extension.hashid.DecodeInt64(str)
			if len(ints) != 1 {
				return
			}`

修改后代码:
`ints, err := extension.hashid.DecodeInt64WithError(str)
if err != nil {iter.Error = err return}
if len(ints) != 1 { return }`

**Comment by liamylian** [comment]
谢谢您的建议，原来的方式的确会造成panic。
