### ISSUE TITLE
如何支持map、slice呢

### ISSUE THREAD

**Issue by guihouchang** [liamylian/json-hashids#2]

**Comment by liamylian** [comment]
> _No description provided._

map 或 slice 中的结构体都是支持的，但是 map[string]int 或 []int 这些是没法直接支持的，因为不能简单的使用 tag 来区分是否需要将其中的 id 序列化为 hashid 还是整数。

对于 map[string]int 或 []int 等情况，建议定义新类型，并实现 **MarshalJSON() ([]byte, error)** 来定制 json 的序列化。
